### ISSUE TITLE
Error when replacing multiple questions

### ISSUE THREAD

**Issue by fom-ds-redcap** [uwctri/CalendarQuestions#1]
Hello, we just installed the module and, after some testing, noticed that the "Replace Questions" functionality would break when trying to replace more than one question. 

Here's our configuration:
<img width="767" alt="Screenshot 2022-04-25 at 3 21 55 PM" src="https://user-images.githubusercontent.com/101148553/165184591-c6d79d96-8286-4dfa-b2fd-c9b64730c2ba.png">

And this is the error in the browser console (Firefox):
<img width="1509" alt="Screenshot 2022-04-25 at 3 22 16 PM" src="https://user-images.githubusercontent.com/101148553/165184588-c0de1cab-4700-483f-b3fd-091aa37c0431.png">

**Comment by aanunez** [comment]
An embarrassing over site. I'll be releasing a fix for this shortly, it should be available on the redcap repo in the next day or two.

**Comment by aanunez** [comment]
I've submitted the new release. Thank you for reporting this!
