### ISSUE TITLE
I can't make it work in REDCap 14

### ISSUE THREAD

**Issue by dmateosj** [uwctri/CalendarQuestions#7]
I'm using php 8.2 and I can't see any question, no matter how i try to configure. 
This project is longitudinal, I dont use any branch or range, just trying to see the question next calendar

![image](https://github.com/uwctri/CalendarQuestions/assets/76000914/7cc2a2df-4338-4929-b829-23e920686c41)

**Comment by aanunez** [comment]
Howdy. The calendar requires that some range be defined for questions to be shown. If you just want to show a very large range and enter data for that range you can just create start/end fields and use @CALCDATE to set them to something large.
